version: '2'
services:
  app:
    build: "."
    container_name: "vst"
    image: "vst"
    volumes:
      - ".:/var/www/vampire-survivors-tools"
    environment:
      APP_ENV: "dev"
    ports:
      - "80:80"
